### ISSUE TITLE
MemoryModule function errors on execution

### ISSUE THREAD

**Issue by rkbennett** [naksyn/PythonMemoryModule#1]
This is caused by a couple issues, at least in my python instance (3.10.x).

The first issue seems to be that in pefile.py ordlookup isn't defined on import

The second issue is related to importordinal in `__init__` which in python3.10 doesn't have a decode method.

**Comment by rkbennett** [comment]
I'm using 3.10.9 on Windows 11, the ordlookup issue was preventing me from even importing pythonmemorymodule

**Comment by rkbennett** [comment]
Also, should say my python was installed through the microsoft store.

**Comment by naksyn** [comment]
thanks for the information. 
This comes up in code used to handle dlls with import ordinal entries and I suppose that's the case for the dll you're loading.
Will merge your PR to correct this. Thanks!

**Comment by rkbennett** [comment]
NP, thanks for taking a look into it.
