### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by DataReset** [naksyn/PythonMemoryModule#4]
first question: why i cant just run exe without arguments?
it throws an error `TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`
second question: does is support nuitka executable? ( i tried, but it doesn't work )
`DEBUG: Starting new thread to execute PE
DEBUG: Checking for entry point.
DEBUG: Calling exe entrypoint 0x140001125`
and nothing then

**Comment by naksyn** [comment]
Hi, yes you can run exe without arguments, should be solved with commit https://github.com/naksyn/PythonMemoryModule/commit/9bb2f6761d17177798e739b7c5160267e569a9cb.
Never tried nuitka executables with pythonmemorymodule, don't know if that would work.

**Comment by DataReset** [comment]
okey, i will try then
