### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by DataReset** [naksyn/PythonMemoryModule#6]
so, i tried it with nuitka executable, everything seems to be fine, no errors, but executable isn't runned, though debug prints that entry point is called

**Comment by naksyn** [comment]
Thanks for letting me know. 
However I won't add support for nuitka executables because I think there are better ways to execute python code in memory instead of using pythonmemorymodule with a nuitka executable. 
Feel free to submit a PR if you can add support for it though.

Cheers

**Comment by naksyn** [comment]
won't fix

**Comment by DataReset** [comment]
can u tell me these methods then? i just need an ability to compile python to exe and then run dynamically from memory.

**Comment by naksyn** [comment]
https://www.xorrior.com/In-Memory-Python-Imports/
